# pip.conf gopls Itchat--save-dev";]"pipx install Itchat"----save-dev") run start"]>>
pip install Itchat--save-dev")
npm i node --V gopls Itchat--save-dev"]>>
#  pip.conf Itchat--save-dev")
#  *egg* *egg* *egg* !water !baboon !friend !miss !you !my !name !antonio !love !you !Itchat
